### PR TITLE
Make diff ids more unique when saving them in Chrome local storage

### PR DESCRIPTION
**Pull request by gholtslander-va**
@Yatser @tmosmant 

This grabs some of the schema.org item properties from the DOM to generate a unique pull request ID for each diff.

Ah, I forgot to add the 'ppr' bit at the beginning for a scope in local storage, I will add that in shortly.

### CODE REVIEW

**Comment by gholtslander-va** [comment]
'ppr' bit is added! Woo

**Comment by tmosmant** [comment]
There's still a bug that you can reproduce this way:

1. Got to the commit list of a PR (ex: https://github.com/Yatser/prettypullrequests/pull/37/commits)
2. Click on a commit
3. Select a file and collapse it
4. Use the back button of your browser
5. Go to the PR "Files changed" section
6. Now try to collapse the previously selected file

This won't work properly. In fact, the collected page infos are the ones of the previously seen commit, so everything you'll do here only affect this commit. The call to `collectUniquePageInfo()` isn't at the right place and except calling this function at each click, I've no solution at this time.

Except that, this works great!

**Comment by gholtslander-va** [comment]
Thanks for the feedback, I'll try that out.

**Comment by gholtslander-va** [comment]
Interesting, I can't reproduce what you're seeing... that shouldn't be a problem in our case because we "collect unique page info" whenever we need to inject the HTML, which should be every time the HTML changes even if it's by PJAX (like with the back button).

I tried the steps you described and couldn't reproduce, sorry :umbrella:

**Comment by tmosmant** [comment]
I don't see where we observe PJAX events, but forget about it, it's not a recurrent problem I think.

**Comment by gholtslander-va** [comment]
We don't really as such, but we check to see if the HTML has changed and our stuff has been removed.

If it becomes a bigger bug we can definitely take a closer look... but it seems alright to me for now. Paging @Yatser for a look and potential merge

**Comment by Yatser** [comment]
Looks good to me

**Pull request merged**
