### PR TITLE
Limit to GitHub.com

### PR DESCRIPTION
**Pull request by bfred-it**
It shouldn't have access to _all_ sites

screen shot 2016-07-13 at 23 15 45

### CODE REVIEW

**Comment by bfred-it** [comment]
I realized that this would need a few more changes, like `optional_permissions`, the ability to change the above addresses once the user defines an enterprise URL, and [permission requests](https://developer.chrome.com/extensions/permissions) in the same moment.

**Comment by Yatser** [comment]
Yes, agreed, I have had plans in the past to explore using optional permissions that occur when a user enters an enterprise URL. I have had at least one other person complain that the permissions are too wide (they never were before people requested enterprise support, and submitted a PR to do it. I was concerned at the time but went with it anyway). 

I haven't put time into looking into it yet... so I do not yet know if it's even possible to do an optional permission that way. I believe you would HAVE to declare your enterprise URL in the manifest ahead of time as an optional permission (however... we could do the wide open permissions as optional, and the github URL's as non optional). That would probably satisfy all parties... if you are using github enterprise and you don't want the wide open permissions, simply fork my chrome extension.

**Comment by bfred-it** [comment]
Yeah, you can specify `https://*/*` as an optional permission and then just request the specific domain:

```js
chrome.permissions.request({
          permissions: ['tabs'], // tabs from the example to match the screenshot
          origins: ['http://www.google.com/']
});
```

**Comment by Yatser** [comment]
@bfred-it are you going to modify this PR to account for the optional permissions?

**Comment by bfred-it** [comment]
This is the current permissions sheet:

Read and change your data on github.com. Read your browsing history


It still asks for 'browsing history' because of `tabs`. I tried removing that permission but it's needed to enable/disable the popup depending on the page/domain. I couldn't find a way around it. The alternative is to have the popup always enabled, but only show its content when visiting GH.

**Comment by Yatser** [comment]
This looks really good. I will get it tested and merged soon. Thank you very much for your contribution @bfred-it

**Comment by Yatser** [comment]
@bfred-it I just wanted to give you an update... I haven't been able to test this and release it yet, but still very much intend on doing so, I've just been really busy. I just want to double check a few things work as I would expect with optional permissions. Please don't be offended if I don't get this merged right away, I believe this is the right solution and I will definitely get it in when I can!

**Comment by bfred-it** [comment]
No worries, some of my pending PRs are about to enter high school :(

**Comment by Yatser** [comment]
I'll test and release this tonight! Thanks again @bfred-it

**Comment by bfred-it** [comment]
Did this work? It doesn't look like content_scripts are loaded on the new origins :|

**Pull request merged**
