### PR TITLE
UX Fixes for Enterprise

### LINKED ISSUE #43: JS Not Loaded on GitHub Enterprise
First of all, great plugin!

This worked well for me for a couple weeks and now I'm unable to get the js to load on GH enterprise pages. It works as expected on non-GHE pages.

I've disabled all other plugins and I still can't get GHE PR files to toggle. When I use the dev tools inspector I can see that the plugin never loads its js/css. However, regular GH pages load the js/css correctly.

I get prompted for new permissions when I enter the GHE url in the options, but I see no change in functionality. I'm wondering if other GHE users have experienced recent degradation.

Thanks for any help. This plugin helps very well w/ managing PRs.

### PR DESCRIPTION
**Pull request by rianrainey**
@gholtslander-va I couldn't seem to have permission to add my commit to your branch so I had to fork and make the PR this way. Feel free to add my commits to your PR or use this PR. My commit got the toggling to work correctly. However, the bottom toggling still doesn't work. Need to look at that.

Fixes #43

### CODE REVIEW

**Comment by gholtslander-va** [comment]
@rianrainey you aren't a member of the project so you can't contribute directly to my branch unfortunately. Forking and making your own is the right way to go 👍 so thanks for that.

**Comment by rianrainey** [comment]
@gholtslander-va Good. Want me to try to get the bottom collapse working before merging this?

**Comment by gholtslander-va** [comment]
Sounds good, it's working in the non-Enterprise version so it'd be nice to get it working in the Enterprise!

**Comment by Yatser** [comment]
Let me know when we want to release this! Thanks for the contribution @rianrainey

**Comment by scottoffen** [comment]
I'd rather have these changes release w/o the bottom bar for how long this is taking. Currently, this plugin isn't working on enterprise at all.

**Comment by rianrainey** [comment]
Okay, the bottom collapse is fixed now for Enterprise. This should be ready to be merged. Let me know if you want any modification or changes. Thanks!

**Comment by Yatser** [comment]
Releasing this right now, expect the changes to roll out in an hour or whatever it takes.

**Pull request merged**
